namespace NinjaBoard.Model
{
    public enum Coin
    {
        Black_Rook_1,
        Black_Rook_2,
        Black_Knight_1,
        Black_Knight_2,
        Black_Bishop_1,
        Black_Bishop_2,
        Black_Queen,
        Black_King,
        Black_Pawn_1,
        Black_Pawn_2,
        Black_Pawn_3,
        Black_Pawn_4,
        Black_Pawn_5,
        Black_Pawn_6,
        Black_Pawn_7,
        Black_Pawn_8,
        White_Rook_1,
        White_Rook_2,
        White_Knight_1,
        White_Knight_2,
        White_Bishop_1,
        White_Bishop_2,
        White_Queen,
        White_King,
        White_Pawn_1,
        White_Pawn_2,
        White_Pawn_3,
        White_Pawn_4,
        White_Pawn_5,
        White_Pawn_6,
        White_Pawn_7,
        White_Pawn_8
    }
}